kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-028-green
nodes:
- role: control-plane
  image: kindest/node:v1.25.11@sha256:227fa11ce74ea76a0474eeefb84cb75d8dad1b08638371ecf0e86259b35be0c8
  extraMounts:
      - hostPath: ./encryption_config.yml
        containerPath: /etc/kubernetes/pki/encryption_config.yml
        readOnly: true
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        encryption-provider-config: "/etc/kubernetes/pki/encryption_config.yml"
      extraVolumes:
          - name: "encryption-config"
            hostPath: "/etc/kubernetes/pki/encryption_config.yml"
            mountPath: "/etc/kubernetes/pki/encryption_config.yml"
            readOnly: true
            pathType: File
