apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-061-red3
  namespace: default
spec:
  selector:
    matchLabels:
      CustodianRule: ecc-k8s-061-minimize_the_admission_of_windows_hostprocess_cont
      ComplianceStatus: Red3
  replicas: 1
  template:
    metadata:
      labels:
        CustodianRule: ecc-k8s-061-minimize_the_admission_of_windows_hostprocess_cont
        ComplianceStatus: Red3
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 0
      containers:
      - name: container-windows-server-iis-061-red3
        image: mcr.microsoft.com/powershell:lts-nanoserver-1809
        command:
          - powershell.exe
          - -command
          - |
              $AdminRights = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]"Administrator")
              Write-Host "Process has admin rights: $AdminRights"
              while ($true) { Start-Sleep -Seconds 2147483 }
        securityContext:
          windowsOptions:
            hostProcess: true
            runAsUserName: "NT AUTHORITY\\system"
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: windows
