# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-k8s-072-readonly_filesystem_is_configured
    resource: k8s.pod
    description: |
      Containers filesystem is not read-only
    filters:
      - not:
        - or:
          - type: value
            key: spec.containers[*].security_context.read_only_root_filesystem
            value: true
            op: in
            value_type: swap
          - type: value
            key: spec.init_containers[*].security_context.read_only_root_filesystem
            value: true
            op: in
            value_type: swap
          - type: value
            key: spec.ephemeral_containers[*].security_context.read_only_root_filesystem
            value: true
            op: in
            value_type: swap

