# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-k8s-074-prefer_using_secrets_as_files_over_secrets_as_environment_variables_for_pod
    comment: '000333262300'
    description: |
      Secrets are used as environment variables for Pod
    resource: k8s.pod
    filters:
      - type: value
        key: |
          spec.containers[].env[].value_from.secret_key_ref || 
          spec.containers[].env_from[].secret_ref
        value: not-null
