# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

policies:
  - name: ecc-k8s-052-default_namespace_should_not_be_used_for_deployment
    description: |
      The default namespace is used for deployment
    resource: k8s.deployment
    filters:
      - type: value
        key: metadata.namespace
        value: default

