kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-039-red-2
nodes:
- role: control-plane
  image: kindest/node:v1.25.11@sha256:227fa11ce74ea76a0474eeefb84cb75d8dad1b08638371ecf0e86259b35be0c8
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    scheduler:
        extraArgs:
          bind-address: "0.0.0.0"
