kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-017-green
nodes:
- role: control-plane
  image: kindest/node:v1.25.11@sha256:227fa11ce74ea76a0474eeefb84cb75d8dad1b08638371ecf0e86259b35be0c8
  extraMounts:
      - hostPath: audit
        containerPath: /audit

  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          audit-log-path: "/audit/audit.log"
          audit-policy-file: "/audit/audit-policy.yaml"
        extraVolumes:
          - name: "audit"
            hostPath: "/audit"
            mountPath: "/audit"
            pathType: DirectoryOrCreate