kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-009-green
nodes:
- role: control-plane
  image: kindest/node:v1.25.11@sha256:227fa11ce74ea76a0474eeefb84cb75d8dad1b08638371ecf0e86259b35be0c8
  extraMounts:
      - hostPath: ./admission-control-config.yaml
        containerPath: /etc/kubernetes/admission-control-config.yaml
        readOnly: true
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: "NodeRestriction,EventRateLimit"
        admission-control-config-file: "/etc/kubernetes/admission-control-config.yaml"
      extraVolumes:
          - name: "admission-control-config"
            hostPath: "/etc/kubernetes/admission-control-config.yaml"
            mountPath: "/etc/kubernetes/admission-control-config.yaml"
            readOnly: true
            pathType: File
